#!/bin/bash
# Script to help troubleshoot and deploy backend fixes to Hugging Face Space

echo "=== Todo App Backend Deployment Helper ==="
echo ""
echo "Files created/updated:"
echo "- requirements.txt - Python dependencies"
echo "- app.py - Hugging Face Space entry point"
echo "- Dockerfile - Container configuration"
echo "- space.yaml - Hugging Face Space configuration"
echo "- .env.example - Environment variables example"
echo "- BACKEND_README.md - Documentation"
echo ""
echo "Steps to deploy these fixes to your Hugging Face Space:"
echo ""
echo "1. Commit these changes to your repository:"
echo "   git add ."
echo "   git commit -m 'Fix backend configuration for Hugging Face Space'"
echo "   git push origin main"
echo ""
echo "2. Go to your Hugging Face Space at:"
echo "   https://huggingface.co/spaces/nayla-yousuf-123/todo-app-chatbot-phase3"
echo ""
echo "3. In the space, make sure the environment variables are set:"
echo "   - DATABASE_URL: Your Neon PostgreSQL URL"
echo "   - SECRET_KEY: A secure secret key"
echo "   - GEMINI_API_KEY: Your Google Gemini API key"
echo ""
echo "4. Wait for the space to rebuild (this may take a few minutes)"
echo ""
echo "5. Test the endpoints once the space is ready:"
echo "   - https://nayla-yousuf-123-todo-app-chatbot-phase3.hf.space/"
echo "   - https://nayla-yousuf-123-todo-app-chatbot-phase3.hf.space/api/health"
echo "   - https://nayla-yousuf-123-todo-app-chatbot-phase3.hf.space/test"
echo ""
echo "6. Check the space logs for any errors during startup"
echo ""
echo "If the space remains in 'Preparing' state, check the logs for specific errors."